language: ruby
cache: bundler
dist: xenial

matrix:
  include:
    - rvm: 2.3.8
    - rvm: 2.4.5
    - rvm: 2.5.3
    - rvm: 2.6
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master

bundler_args: --jobs 7 --without docs debug

script: bundle exec rake
